# We run the docker provider by default
ENV['VAGRANT_DEFAULT_PROVIDER'] ||= 'docker'

# The HTTP port can be chosen with the HTTP_PORT environment variable
# e.g. by running "HTTP_PORT=3000 vagrant up"
HTTP_PORT = ENV['HTTP_PORT'] || "8080"

Vagrant.configure(2) do |config|

  config.vm.define "silverstripe" do |app|
    app.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "Vagrantfile.proxy"
      d.image = "<%= image %>"
      d.ports = [ HTTP_PORT + ":80" ]
      d.volumes = ["/vagrant:/var/www"]
      d.has_ssh = false
    end
  end

end
